# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
  primary: true
  type: upstream
  upstream: "testwebbapp:http"
  cache:
    enabled: false

"https://www.{default}/":
  primary: false
  type: upstream
  upstream: "testwebbapp:http"
  cache:
    enabled: false

